services:
  app:
    build:
      context: .
      args:
        APP_VERSION: "${APP_VERSION:-dev}"
    image: grimmory-book-manager:${APP_VERSION:-latest}
    ports:
      - "80:80"
    volumes:
      - ./data:/app/data
    labels:
      - "app.version=${APP_VERSION:-dev}"
    networks:
      - ${NETWORK_NAME:-grimmory-network}

networks:
  grimmory-network:
    external: true
    name: ${NETWORK_NAME:-grimmory-network}
